/**
 * Production Planning Component
 *
 * Calculator for batch production planning with material requirements
 * and time estimates based on selected mold configuration.
 */

import React, { useState, useMemo } from 'react';
import { Card, CardHeader, CardTitle, CardContent } from '../card';
import { Button } from '../button';
import { Package, Clock, Scale, TrendingUp, Download } from 'lucide-react';
import { calculateMaterialRequirements } from '../utils/dimensionsDatabaseLoader';

/**
 * Production Planner Component
 *
 * @param {Object} props
 * @param {Object} props.selectedMold - Currently selected mold configuration
 * @param {boolean} props.isVisible - Whether component is visible
 */
export function ProductionPlanner({ selectedMold, isVisible = true }) {
  const [quantity, setQuantity] = useState(100);
  const [shiftsPerDay, setShiftsPerDay] = useState(1);
  const [hoursPerShift, setHoursPerShift] = useState(8);
  const [foamDensity, setFoamDensity] = useState(40);
  const [mixRatio, setMixRatio] = useState({ polyol: 100, iso: 110 });
  const [wasteFactor, setWasteFactor] = useState(5); // percentage

  // Calculate production metrics
  const metrics = useMemo(() => {
    if (!selectedMold) return null;

    const materialReqs = calculateMaterialRequirements(
      selectedMold,
      quantity,
      foamDensity,
      mixRatio
    );

    const hoursPerDay = shiftsPerDay * hoursPerShift;
    const partsPerDay = materialReqs.parts_per_hour * hoursPerDay;
    const daysRequired = Math.ceil(quantity / partsPerDay);

    // Add waste factor
    const actualPolyol = materialReqs.polyol_needed_kg * (1 + wasteFactor / 100);
    const actualIso = materialReqs.iso_needed_kg * (1 + wasteFactor / 100);
    const actualTotal = materialReqs.total_material_kg * (1 + wasteFactor / 100);

    return {
      ...materialReqs,
      polyol_with_waste_kg: actualPolyol,
      iso_with_waste_kg: actualIso,
      total_with_waste_kg: actualTotal,
      parts_per_day: partsPerDay,
      days_required: daysRequired,
      total_production_hours: (quantity / materialReqs.parts_per_hour)
    };
  }, [selectedMold, quantity, foamDensity, mixRatio, shiftsPerDay, hoursPerShift, wasteFactor]);

  const exportToCSV = () => {
    if (!metrics || !selectedMold) return;

    const csv = [
      ['Production Planning Report'],
      [''],
      ['Mold Information'],
      ['Mold ID', selectedMold.mold_id],
      ['Type', selectedMold.type],
      ['Shape', selectedMold.shape],
      ['Volume per Part (L)', selectedMold.volume_liters],
      [''],
      ['Production Parameters'],
      ['Quantity', quantity],
      ['Foam Density (kg/m³)', foamDensity],
      ['Mix Ratio (Polyol:Iso)', `${mixRatio.polyol}:${mixRatio.iso}`],
      ['Waste Factor (%)', wasteFactor],
      [''],
      ['Schedule'],
      ['Shifts per Day', shiftsPerDay],
      ['Hours per Shift', hoursPerShift],
      ['Hours per Day', shiftsPerDay * hoursPerShift],
      [''],
      ['Material Requirements'],
      ['Polyol Needed (kg)', metrics.polyol_needed_kg.toFixed(2)],
      ['Iso Needed (kg)', metrics.iso_needed_kg.toFixed(2)],
      ['Total Material (kg)', metrics.total_material_kg.toFixed(2)],
      [''],
      ['With Waste Factor'],
      ['Polyol with Waste (kg)', metrics.polyol_with_waste_kg.toFixed(2)],
      ['Iso with Waste (kg)', metrics.iso_with_waste_kg.toFixed(2)],
      ['Total with Waste (kg)', metrics.total_with_waste_kg.toFixed(2)],
      [''],
      ['Production Timeline'],
      ['Parts per Hour', metrics.parts_per_hour],
      ['Parts per Day', metrics.parts_per_day.toFixed(1)],
      ['Days Required', metrics.days_required],
      ['Total Production Hours', metrics.total_production_hours.toFixed(1)],
      [''],
      ['Generated by PU Injection Optimizer', new Date().toLocaleString()]
    ].map(row => row.join(',')).join('\n');

    const blob = new Blob([csv], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `production_plan_${selectedMold.mold_id}_${quantity}pcs.csv`;
    a.click();
    window.URL.revokeObjectURL(url);
  };

  if (!isVisible || !selectedMold) return null;

  return (
    <Card className="border-2 border-purple-200 bg-gradient-to-br from-purple-50 to-pink-50">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Package className="h-5 w-5 text-purple-600" />
          Production Planning
          <span className="text-sm text-gray-500 font-normal">
            Batch Calculator
          </span>
        </CardTitle>
      </CardHeader>

      <CardContent className="space-y-6">
        {/* Mold Info */}
        <div className="p-3 bg-white border border-purple-200 rounded-lg">
          <div className="font-semibold text-sm text-purple-900 mb-1">Selected Mold:</div>
          <div className="text-sm">
            <span className="font-medium">{selectedMold.type}</span>
            <span className="text-gray-600 ml-2">({selectedMold.volume_liters.toFixed(2)}L per part)</span>
          </div>
        </div>

        {/* Input Parameters */}
        <div className="grid grid-cols-2 gap-4">
          {/* Quantity */}
          <div>
            <label className="block text-sm font-medium mb-1">
              <Package className="h-4 w-4 inline mr-1" />
              Quantity (parts)
            </label>
            <input
              type="number"
              value={quantity}
              onChange={(e) => setQuantity(Math.max(1, parseInt(e.target.value) || 1))}
              className="w-full p-2 border rounded focus:ring-2 focus:ring-purple-500"
              min="1"
            />
          </div>

          {/* Foam Density */}
          <div>
            <label className="block text-sm font-medium mb-1">
              <Scale className="h-4 w-4 inline mr-1" />
              Foam Density (kg/m³)
            </label>
            <input
              type="number"
              value={foamDensity}
              onChange={(e) => setFoamDensity(Math.max(20, parseInt(e.target.value) || 40))}
              className="w-full p-2 border rounded focus:ring-2 focus:ring-purple-500"
              min="20"
              max="100"
            />
          </div>

          {/* Shifts per Day */}
          <div>
            <label className="block text-sm font-medium mb-1">
              <Clock className="h-4 w-4 inline mr-1" />
              Shifts per Day
            </label>
            <select
              value={shiftsPerDay}
              onChange={(e) => setShiftsPerDay(parseInt(e.target.value))}
              className="w-full p-2 border rounded focus:ring-2 focus:ring-purple-500"
            >
              <option value="1">1 shift</option>
              <option value="2">2 shifts</option>
              <option value="3">3 shifts (24h)</option>
            </select>
          </div>

          {/* Hours per Shift */}
          <div>
            <label className="block text-sm font-medium mb-1">
              Hours per Shift
            </label>
            <select
              value={hoursPerShift}
              onChange={(e) => setHoursPerShift(parseInt(e.target.value))}
              className="w-full p-2 border rounded focus:ring-2 focus:ring-purple-500"
            >
              <option value="4">4 hours</option>
              <option value="6">6 hours</option>
              <option value="8">8 hours</option>
              <option value="10">10 hours</option>
              <option value="12">12 hours</option>
            </select>
          </div>

          {/* Waste Factor */}
          <div className="col-span-2">
            <label className="block text-sm font-medium mb-1">
              <TrendingUp className="h-4 w-4 inline mr-1" />
              Waste Factor: {wasteFactor}%
            </label>
            <input
              type="range"
              value={wasteFactor}
              onChange={(e) => setWasteFactor(parseInt(e.target.value))}
              className="w-full"
              min="0"
              max="20"
              step="1"
            />
            <div className="flex justify-between text-xs text-gray-600 mt-1">
              <span>0% (no waste)</span>
              <span>20% (high waste)</span>
            </div>
          </div>
        </div>

        {/* Results */}
        {metrics && (
          <>
            <div className="border-t pt-4">
              <h3 className="font-semibold mb-3 text-purple-900">Material Requirements:</h3>
              <div className="grid grid-cols-2 gap-3 text-sm">
                <div className="p-2 bg-blue-50 rounded">
                  <div className="text-gray-600">Polyol Needed</div>
                  <div className="font-bold text-lg">{metrics.polyol_needed_kg.toFixed(2)} kg</div>
                  <div className="text-xs text-gray-500">+{wasteFactor}%: {metrics.polyol_with_waste_kg.toFixed(2)} kg</div>
                </div>
                <div className="p-2 bg-green-50 rounded">
                  <div className="text-gray-600">Isocyanate Needed</div>
                  <div className="font-bold text-lg">{metrics.iso_needed_kg.toFixed(2)} kg</div>
                  <div className="text-xs text-gray-500">+{wasteFactor}%: {metrics.iso_with_waste_kg.toFixed(2)} kg</div>
                </div>
                <div className="p-2 bg-purple-50 rounded col-span-2">
                  <div className="text-gray-600">Total Material</div>
                  <div className="font-bold text-2xl">{metrics.total_with_waste_kg.toFixed(2)} kg</div>
                  <div className="text-xs text-gray-500">
                    (Base: {metrics.total_material_kg.toFixed(2)} kg + Waste: {wasteFactor}%)
                  </div>
                </div>
              </div>
            </div>

            <div className="border-t pt-4">
              <h3 className="font-semibold mb-3 text-purple-900">Production Timeline:</h3>
              <div className="grid grid-cols-2 gap-3 text-sm">
                <div className="p-2 bg-gray-50 rounded">
                  <div className="text-gray-600">Parts per Hour</div>
                  <div className="font-bold text-lg">{metrics.parts_per_hour}</div>
                </div>
                <div className="p-2 bg-gray-50 rounded">
                  <div className="text-gray-600">Parts per Day</div>
                  <div className="font-bold text-lg">{metrics.parts_per_day.toFixed(1)}</div>
                  <div className="text-xs text-gray-500">{shiftsPerDay} × {hoursPerShift}h shifts</div>
                </div>
                <div className="p-2 bg-orange-50 rounded">
                  <div className="text-gray-600">Days Required</div>
                  <div className="font-bold text-2xl">{metrics.days_required}</div>
                  <div className="text-xs text-gray-500">calendar days</div>
                </div>
                <div className="p-2 bg-orange-50 rounded">
                  <div className="text-gray-600">Total Hours</div>
                  <div className="font-bold text-2xl">{metrics.total_production_hours.toFixed(1)}</div>
                  <div className="text-xs text-gray-500">production time</div>
                </div>
              </div>
            </div>

            {/* Export Button */}
            <Button
              onClick={exportToCSV}
              className="w-full bg-purple-600 hover:bg-purple-700"
            >
              <Download className="h-4 w-4 mr-2" />
              Export Production Plan (CSV)
            </Button>
          </>
        )}
      </CardContent>
    </Card>
  );
}

export default ProductionPlanner;
